### ISSUE TITLE
Training RIFE models

### ISSUE THREAD

**Issue by couleurm** [Bubblemint864/AI-Models#1]
Hey I'd like to train some footage for RIFE NCNN VS frame interpolation as well as resolution upscaling (I'm not sure if there are any VapourSynth  plugins that let you upscale w/ models) , do you know good resources to learn how to make your own models?

**Comment by Bubblemint864** [comment]
Hello!

If you'd like to learn how to train models, I would highly recommend joining the [Enhance Everything](https://discord.gg/cpAUpDK) Discord server and asking in the traiNNer channel or reading the guide on [upscale.wiki](https://upscale.wiki).

As for upscaling with VapourSynth, I would suggest checking out [styler00dollar's Docker container](https://github.com/styler00dollar/VSGAN-tensorrt-docker). I believe it uses [vs-mlrt](https://github.com/AmusementClub/vs-mlrt) and some other stuff; as I am not a VapourSynth user myself, I am a bit useless in this area 😅.
