### ISSUE TITLE
loading model to Real-Esrgan

### ISSUE THREAD

**Issue by hat3l0v3** [Bubblemint864/AI-Models#3]
Don't want to disturb you, i'm newbie, but your 2x_Bubble_AnimeScale_Compact_v1 model says it have Real-Esrgan  architecture. But Real-Esrgan use _**.bin**_ and _**.param**_ files (not **_.pth_**). 
  So I have error `_wfopen ...(path)/models/2x_Bubble_AnimeScale_Compact_v1.param failed`
 
 I tried convert it with Cupscale that convert old Esrgan models but its crashed with error like: 
```
Failed to convert Pytorch model to NCNN format! It might be incompatible.

KeyError: 'model.0.weight'

Stack Trace:
   в Cupscale.OS.NcnnUtils.<ConvertNcnnModel>d__6.MoveNext()

The error message was copied to the clipboard.
```
   Can you help to load this model? Or maybe where I should watch?

**Comment by Bubblemint864** [comment]
Hey, apologies for the late reply.

I believe Cupscale does not support Compact as it has not been updated in more than a year. If you have not already, please consider switching to [chaiNNer](https://github.com/chaiNNer-org/chaiNNer) as it is actively supported and supports Compact. It supports all versions of the model which include .pth, .onnx and .bin & .param. If you plan on upscaling videos I would highly recommend using [enhancr](https://github.com/mafiosnik777/enhancr) instead. The builds are paid but are well worth your money!

However if you would still like to use ncnn, I have now uploaded the bin and param files to the [release](https://github.com/Bubblemint864/AI-Models/releases/tag/2x_Bubble_AnimeScale_Compact_v1). Let me know if they work!

Bubble

**Comment by mafiosnik777** [comment]
> Don't want to disturb you, i'm newbie, but your 2x_Bubble_AnimeScale_Compact_v1 model says it have Real-Esrgan architecture. But Real-Esrgan use _**.bin**_ and _**.param**_ files (not **_.pth_**). So I have error `_wfopen ...(path)/models/2x_Bubble_AnimeScale_Compact_v1.param failed`
> 
> I tried convert it with Cupscale that convert old Esrgan models but its crashed with error like:
> 
> ```
> Failed to convert Pytorch model to NCNN format! It might be incompatible.
> 
> KeyError: 'model.0.weight'
> 
> Stack Trace:
>    в Cupscale.OS.NcnnUtils.<ConvertNcnnModel>d__6.MoveNext()
> 
> The error message was copied to the clipboard.
> ```
> 
> Can you help to load this model? Or maybe where I should watch?

I'm not familiar with Cupscale, but Real-ESRGAN doesn't only use .bin/.param. That's simply the format NCNN inference uses. Try switching to another inference if you can do that in Cupscale or use the before mentioned alternatives Bubblemint gave you.

**Comment by Bubblemint864** [comment]
> I'm not familiar with Cupscale, but Real-ESRGAN doesn't only use .bin/.param. That's simply the format NCNN inference uses. Try switching to another inference if you can do that in Cupscale or use the before mentioned alternatives Bubblemint gave you.

I believe Cupscale is limited to ncnn when it comes to Real-ESRGAN, NMKD should really update it lmao

**Comment by hat3l0v3** [comment]
tried 2x_Bubble_AnimeScale_Compact_v1_ncnn_fp32 - doen't work, its says:
```
find_blob_index_by_name data failed
Try
    ex.input("input", in0);
```
well i tried to use chaiNNer before, install all dependencies, but it not work for me with any model at all, so I deleted it.

**Comment by mafiosnik777** [comment]
@hat3l0v3 
It needs other input names, you can change them up in the param file, or if you're not feeling comfortable with that you can throw Bubblemint a private message on discord and I can do it for you guys.

**Comment by Bubblemint864** [comment]
My advice is: give chaiNNer another shot.

Install all the dependencies to the  built-in python environment rather than your system one through the dependency manager, then copy this chain:
![image](https://user-images.githubusercontent.com/69756370/205111699-26fa546e-ab78-4c0f-b9c0-d2d04e7f1e3a.png)

**Comment by hat3l0v3** [comment]
okay, I run throught chaiNNer and seems works fine.
Anyway thanks for your time.

**Comment by Bubblemint864** [comment]
No problem! Feel free to open another issue for help and star the repo :)
